openapi: 3.0.3
info:
  title: Culture Web API
  description: カルチャーコンテンツ管理システムAPI
  version: 1.0.0
  contact:
    name: Culture Web チーム

servers:
  - url: http://localhost:3000/api/v1
    description: 開発サーバー

# Authentication API endpoints
paths:
  /users:
    post:
      summary: ユーザー登録
      tags: [認証]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    name:
                      type: string
                    email:
                      type: string
                      format: email
                    password:
                      type: string
                      minLength: 6
                    password_confirmation:
                      type: string
                      minLength: 6
                  required: [name, email, password, password_confirmation]
              required: [user]
      responses:
        "201":
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    additionalProperties: false
                    properties:
                      user:
                        type: object
                        additionalProperties: false
                        properties:
                          id:
                            type: integer
                          uuid:
                            type: string
                            format: uuid
                          status:
                            type: string
                            enum: [active, inactive, suspended]
                        required: [id, uuid, status]
                      token:
                        type: string
                        description: JWT認証トークン
                    required: [user, token]
                required: [success, data]
        "422":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationError"

  /users/{id}:
    get:
      summary: Get user information
      tags: [Authentication]
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: User information
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      uuid:
                        type: string
                        format: uuid
                      status:
                        type: string
                        enum: [active, inactive, suspended]
                required: [success, data]
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    patch:
      summary: Update user
      tags: [Authentication]
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    name:
                      type: string
                    email:
                      type: string
                      format: email
                  required: [name, email]
              required: [user]
      responses:
        "200":
          description: User updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      uuid:
                        type: string
                        format: uuid
                      status:
                        type: string
                        enum: [active, inactive, suspended]
                required: [success, data]
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "422":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationError"

  /session:
    post:
      summary: User login
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required: [email, password]
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    additionalProperties: false
                    properties:
                      user:
                        type: object
                        additionalProperties: false
                        properties:
                          id:
                            type: integer
                          uuid:
                            type: string
                            format: uuid
                          status:
                            type: string
                            enum: [active, inactive, suspended]
                        required: [id, uuid, status]
                      token:
                        type: string
                        description: JWT認証トークン
                    required: [user, token]
                required: [success, data]
        "401":
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    delete:
      summary: User logout
      tags: [Authentication]
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Logout successful
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "ログアウトしました"
                required: [success, message]

components:
  schemas:
    # Common Error Types
    Error:
      type: object
      additionalProperties: false
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          example: "invalid_credentials"
        message:
          type: string
          example: "メールアドレスまたはパスワードが正しくありません"
      required: [success, error, message]

    ValidationError:
      type: object
      additionalProperties: false
      properties:
        success:
          type: boolean
          example: false
        errors:
          type: array
          items:
            type: string
          example: ["パスワードは6文字以上で入力してください"]
      required: [success, errors]

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
